[phases.setup]
nixPkgs = ['nodejs', 'python312']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = [
  'npm run build',
  'ls -la medical_clinic/static/css/',
  'python manage.py collectstatic --noinput --clear --verbosity=2'
]

[start]
cmd = 'gunicorn doc_clinic.wsgi:application --bind 0.0.0.0:$PORT'