# Generated by Django 6.0.3 on 2026-03-20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_clinic", "0002_add_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("tag", models.CharField(blank=True, max_length=80)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-occurred_on", "-created_at"],
            },
        ),
    ]

