# Generated by Django 6.0.3 on 2026-03-21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_clinic", "0003_case_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("completed", "Completed"), ("no_show", "No-show")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="confirmation_sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="closure_sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SmsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_phone", models.CharField(max_length=30)),
                ("body", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "appointment_confirmation",
                                "Appointment confirmation",
                            ),
                            ("appointment_closed", "Appointment closed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("error", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="sms_messages",
                        to="medical_clinic.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

