# Generated by Django 6.0.3 on 2026-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_clinic', '0004_appointment_status_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/'),
        ),
    ]
