# Generated by Django 6.0.3 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_clinic', '0006_specialist_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
                ('maps_query', models.CharField(blank=True, max_length=300)),
                ('maps_open_url', models.URLField(blank=True)),
                ('maps_embed_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic settings',
                'verbose_name_plural': 'Clinic settings',
            },
        ),
    ]
